name: globgram_p2p
description: A peer-to-peer chat application with voice messaging capabilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # P2P Communication
  flutter_webrtc: ^0.11.5
  
  # Firebase for Signaling
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Internationalization
  easy_localization: ^3.0.3
  intl: 0.20.2
  
  # UI Components
  emoji_picker_flutter: ^1.6.4
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utils
  uuid: ^4.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  file_picker: ^6.1.1
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/translations/
    - assets/images/
    - assets/sounds/

flutter_intl:
  enabled: true
